default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: xmas_development

test:
  <<: *default
  database: xmas_test

production:
  pool: 5
  database: <%= ENV['DATABASE_URL'] %>
  cache:
    pool: 5
    database: xmas_production_cache
    migrations_paths: db/cache_migrate
  queue:
    pool: 5
    database: xmas_production_queue
    migrations_paths: db/queue_migrate
  cable:
    pool: 5
    database: xmas_production_cable
    migrations_paths: db/cable_migrate
