default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: xmas_development

test:
  <<: *default
  database: xmas_test

production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    database: <%= ENV['DATABASE_URL'] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  cache:
    <<: *primary_production
    database: xmas_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: xmas_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: xmas_production_cable
    migrations_paths: db/cable_migrate
